DROP TABLE IF EXISTS Album CASCADE;
DROP TABLE IF EXISTS Band CASCADE;
DROP TABLE IF EXISTS BandMember CASCADE;
DROP TABLE IF EXISTS AppUser CASCADE;
DROP TABLE IF EXISTS UserAlbum CASCADE;
DROP TABLE IF EXISTS Track CASCADE;
